add support for long flags in setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -108,7 +108,7 @@ stow_all() {
     fi
 }
 
-full_installation() {
+full_install() {
     echo "Stow all dotfiles"
     stow_all
 
@@ -125,7 +125,7 @@ full_installation() {
     echo "Installation complete!"
 }
 
-full_uninstallation() {
+full_uninstall() {
     echo "Unstow all dotfiles"
     stow_all
 
@@ -141,44 +141,45 @@ full_uninstallation() {
     echo "Installation complete!"
 }
 
-parse_flags() {
-    while getopts sad:t: opt
-    do
-        case $opt in
-        s)
-            SIMULATE=true ;;
-        a)
-            ALL=true ;;
-        d)
-            DOTS_DIR=$OPTARG ;;
-        t)
-            TARGET_DIR=$OPTARG ;;
-        \?)
-            help
-            exit 1 ;;
+parse_global_flags() {
+    while [ $# -gt 0 ]; do
+        case $1 in
+        -s|--simulate) SIMULATE=true ;;
+        -a|--all) ALL=true ;;
+        -d|--dots) DOTS_DIR=$2; shift ;;
+        -t|--target) TARGET_DIR=$2; shift ;;
+        -*) echo "$0: error - unrecognized option \"$1\"" 1>&2; help; exit 1;;
+        *) break ;;
         esac
+        shift
     done
+    # set global args array to remaining params
+    args=($@)
 }
+
+declare -a args
 
 subcommand=${1:-""}
 case $subcommand in
     "install")
         shift
-        parse_flags "$@"
+        parse_global_flags "$@"
         ALL=true
         UNSTOW=false
-        full_installation
+        full_install
         ;;
     "uninstall")
         shift
-        parse_flags "$@"
+        parse_global_flags "$@"
         ALL=true
         UNSTOW=true
-        full_uninstallation
+        full_uninstall
         ;;
     "stow")
         shift
-        parse_flags "$@"
+        parse_global_flags "$@"
+        # set args to positional params
+        set -- "${args[@]}"
         UNSTOW=false
         if $ALL ; then
             stow_all
@@ -188,7 +189,8 @@ case $subcommand in
         ;;
     "unstow")
         shift
-        parse_flags "$@"
+        parse_global_flags "$@"
+        set -- "${args[@]}"
         UNSTOW=true
         if $ALL ; then
             stow_all
@@ -199,8 +201,8 @@ case $subcommand in
     "" | "-h" | "--help" | "help")
         help
         exit 1 ;;
+    *)
+        echo "$0: error - unrecognized command \"$1\""
+        help
+        exit 1 ;;
 esac
-
-shift $((OPTIND-1))
-
-
